### ISSUE TITLE
Can we save streaming in local storage

### ISSUE THREAD

**Issue by vedraj360** [warren-bank/Android-RTSP-IPCam-Viewer#7]
First of all I want to say thank you for making this repository It really saved lot of time. 
I want to ask you that is it possible to save the live streaming in local storage.

**Comment by warren-bank** [comment]
Hi. Unfortunately, ExoPlayer doesn't include the ability to save any of its supported stream formats to a local file for offline replay.

This project started as an experiment with using ExoPlayer to play RTSP streams back when support for that format wasn't official, and only existed in a pull request that had been open for years.

I'm very happy to see that this feature has finally been merged and RTSP is now an officially supported stream format. However, that makes this project less interesting. I did update to a stable version of ExoPlayer after this support was added. Now, this app is really just an example of how to include ExoPlayer in a Recycler view. I did not, however, update the app to support all of the other vast formats that ExoPlayer also supports, since the UI of the app probably wouldn't make much sense for any other use cases.. for example.. watching multiple TV channels at once.

Back to your original question.. ExoPlayer does include the ability to cache a stream, but there's no way to write this cache to a standard video file format. I wish we could. It seems like this was a deliberate decision on the part of their dev team. The topic has been asked again-and-again as an issue in ExoPlayer's [github repo](https://github.com/google/ExoPlayer).
